export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_OTHER_PROFILE_USERNAME = 'UPDATE_OTHER_PROFILE_USERNAME';
export const UPDATE_OTHER_PROFILE_DETAILS = 'UPDATE_OTHER_PROFILE_DETAILS';